---
- name: manage webserver
  hosts: appserver
  remote_user: centos
  gather_facts: true
  become: true
#  vars_prompt:
#    name: service_name
#    prompt: 'enter service name'
#  vars:
#     service_name: sshd

  handlers:
  - name: restart_webservice
    service:
        name: "{{service_name}}"
        state: restarted

  tasks:
  - name: install webserver
    package:
        name: "{{package_name}}"
        state: present

  - name: manage service
    service:
        name: "{{service_name}}"
        state: started

  - name: deploy site
    copy:
        src: index.html
        dest: "/var/www/html/"
    notify:
        restart_webservice

- name: manage users
  hosts: jenkins
  remote_user: centos
  gather_facts: false
  become: true
  tasks:
  - name: manage users
    user:
        name: "{{user_name}}"
        state: present



