
- name: manage webserver
  hosts: appserver
  remote_user: centos
  gather_facts: false
  become: true

  tasks:
  - name: install webserver
    package:
        name: "{{package_name}}"
        state: present

  - name: manage service
    service:
        name: "{{service_name}}"
        state: started

  - name: deploy site
    copy:
        src: index.html
        dest: "/var/www/html/"



