---
# tasks file for webserver

  - name: install webserver
    when: ansible_facts['os_family'] == "RedHat"
    package:
        name: "{{package_name}}"
        state: present

  - name: manage service
    service:
        name: "{{service_name}}"
        state: started

  - name: deploy site
    copy:
        src: index.html
        dest: "/var/www/html/"
    notify:
        restart_webservice

  - include: user.yml

